; CDDL for draft-frost-rats-eat-collection, suitable for standalone testing

; $$EAT-CBOR-Tagged-Token /= Tagged-Collection
; $$EAT-CBOR-Untagged-Token /= TL-Collection

; NB: label is TBD, temp value used here
; TODO add makefile and substitute for TBD
Tagged-Collection =  #6.399(TL-Collection)

TL-Collection = {
    ? eat-collection-identifier,
    + all-collection-types
}

eat-collection-identifier = (
    profile-label => general-uri / general-oid
)

all-collection-types = (
    cwt-collection-entries //
    jwt-collection-entries //
    claim-set-collection-entries //
    detatched-eat-bundle-collection-entries
)

cwt-collection-entries = (
    collection-entry-label => CWT-Messages
)

jwt-collection-entries = (
    collection-entry-label => JWT-Messages
)

claim-set-collection-entries = (
    collection-entry-label => JC<json-wrapped-claims-set, 
                                 cbor-wrapped-claims-set>
)

detatched-eat-bundle-collection-entries = (
    collection-entry-label => BUNDLE-Messages
)

collection-entry-label = JC<text, int>

; The Collection Binder is a formal declaration of the inter entry binding
; mechanism. It would be included within the body of one or more of the
; collection entries. 
Tagged-Collection-Binder =  #6.99(Collection-Binder)
Collection-Binder = [
    binder-function,
    [*binder-source-label],
    destination-collection-entry,
    destination-claim
]
; binder function is normally the name/id of a hash algorithm
binder-function = JC<text,int>

; by definition, the binder-function is applied to a concatenation of the
; ordered list of source claims
; If the array is empty, the function is applied to the whole contents of
; the token
binder-source-label = Claim-Label

destination-collection-entry = collection-entry-label

destination-claim = Claim-Label


; required placeholders for standalone checking
CWT-Messages = bstr .cbor CWT-placeholder
JWT-Messages = "jwt-placeholder"
BUNDLE-Messages = "detached-EAT-bundle-placeholder"
CWT-placeholder = "cwt-placeholder"
general-uri = "General URI placeholder"
general-oid = "General OID placeholder"
profile-label = JC<"eat_profile", 265>
Claim-Label = JC<"text", int>
json-wrapped-claims-set="json-wrapped-claims-set-placeholder"
cbor-wrapped-claims-set="cbor-wrapped-claims-set-placeholder"
JC<J,C> = J .feature "json" / C .feature "cbor"
