; CDDL for draft-frost-rats-eat-collection, suitable for standalone testing

; $$EAT-CBOR-Tagged-Token /= Tagged-Collection
; $$EAT-CBOR-Untagged-Token /= TL-Collection

; NB: label is TBD, temp value used here
; TODO add makefile and substitute for TBD
Tagged-Collection =  #6.399(TL-Collection)

; Note that although the common use cases for collections are for at
; least two entries in a collection, the CDDL below allows for >= 1
; entry to allow the scenario where only one entry is currently
; available even ; though the normal set is larger
TL-Collection = {
    ? eat-collection-identifier,
    + all-collection-types
}

eat-collection-identifier = (
    profile-label => general-uri / general-oid
)

all-collection-types = (
    cwt-collection-entries // jwt-collection-entries // DEB-collection-entries
)

cwt-collection-entries = (
    collection-entry-label => CWT-Messages
)

jwt-collection-entries = (
    collection-entry-label => JWT-Messages
)

DEB-collection-entries = (
    collection-entry-label => DEB-Messages
)

collection-entry-label = JC<text, int>

; required placeholders for standalone checking
CWT-Messages = bstr .cbor CWT-placeholder
JWT-Messages = "jwt-placeholder"
DEB-Messages = "DEB-placeholder"
CWT-placeholder = "cwt-placeholder"
general-uri = "General URI placeholder"
general-oid = "General OID placeholder"
profile-label = JC<"eat_profile", 265>
JC<J,C> = J .feature "json" / C .feature "cbor"
